language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kopfyf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kopfyf/docker-react npm run test
  # - docker run kopfyf/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-041496910032"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

